### ISSUE TITLE
博客使用？

### ISSUE THREAD

**Issue by anxingle** [willard-yuan/willard-yuan.github.io#1]
你好，关注您好久了。知乎上还留言了（发现小白菜就是袁勇）。请问您的博客如何使用呢？如果我fork了，增加一条博客，要在哪里增加呢？修改哪几个文件呢？例如我的博客（anxingle.github.io）修改：

在post文件夹下新建文件，文件名为：日期+标题，文件以.md结尾，例如：2012-12-12-hello-world.md

修改post/index.json文件，其中

site_name为站点名称； copyright 为版权标示； cates为文章分类； articles为文章列表。

例如

增加2012-12-12-hello-world.md,articles中增加一条记录

{"title": "Hello World", "file": "2012-12-12-hello-world", "cate":"tech"},
评论修改： 修改index.html中的

var duoshuoQuery = {short_name:"hugcoday"};

我也想用您的博客模板！

**Comment by willard-yuan** [comment]
哈哈，原来你也是中科院的。这个博客被我改得有点乱，什么时候那个地方不爽了就改一下，所以整体的结构还是很混乱的，不过要套用这个模板还是完全可以的，遵行下面的步骤应该可以成功。
1. 把模板下载过去，如果你没有用单独的域名的话，把`CNAME`文件删掉，然后顺便把`_posts`里的文章删掉，可以留一篇，方便后面用markdown时对文章格式做参考；
2. 配置`_config.yml`，比如把title修改成你自己；
3. 修改英文页面[default.html](https://github.com/willard-yuan/willard-yuan.github.io/blob/master/_layouts/default.html)，把里面出现的固定的url更改成你的url；
4. 修改中文页面[index.html](https://github.com/willard-yuan/willard-yuan.github.io/blob/master/cn/index.html)，主要是中文页面的一些内容；
5. **contact**目录这个里面的东西没用，我虽没删，但从没有用过，你觉得碍眼的话，完全可以把这个目录删掉，不会造成任何影响；
6. **resume**目录是在线简历，[演示效果](http://yongyuan.name/resume/)，这个你在用时，把前面那个[default.html](https://github.com/willard-yuan/willard-yuan.github.io/blob/master/_layouts/default.html)中把latex的简历url换成这个目录的url；
7. **book**模板，这个你需要有一个豆瓣账号，现在[books/index.html](https://github.com/willard-yuan/willard-yuan.github.io/blob/master/books/index.html)页面把title等修改一下，然后到[douban.api.js](https://github.com/willard-yuan/willard-yuan.github.io/blob/master/js/douban.api.js)把账号user和api改一下。

上面7步改完了，应该就没什么问题了，有问题你可以再联系我。

**Comment by anxingle** [comment]
谢谢您啊！
