### ISSUE TITLE
博客的tag为什么是404页面？

### ISSUE THREAD

**Issue by esperisto** [willard-yuan/willard-yuan.github.io#2]
你好！
请问你博客的tag为什么是404页面？我觉得你的博客挺好看的，所以就clone了。但是我看你博客文章的tag，点击进去后是404。请问如何解决？

**Comment by willard-yuan** [comment]
@esperisto tag这个功能没有写，categories和tag两个功能有些交叉，所以暂时用的categories来对文章进行归档。

**Comment by esperisto** [comment]
哦，好的，谢谢。

**Comment by handbye** [comment]
有时间修复下，感谢袁哥~~
