### ISSUE TITLE
大佬能给个联系方式吗，想学图像搜索这块的技术

### ISSUE THREAD

**Issue by xxllp** [willard-yuan/willard-yuan.github.io#6]

**Comment by willard-yuan** [comment]
@xxllp 我博客里面有很多关于图像搜索的博文，可以先从那里学习。等学得差不多了，再找我要联系方式吧。

**Comment by xxllp** [comment]
你的项目里面有 sift  bovw VLAD 整套的例子吗 ，博客我基本都看了下，大致了解了

**Comment by willard-yuan** [comment]
BOW 模型可以参考这里[BoW图像检索原理与实战](http://yongyuan.name/blog/CBIR-BoW-for-image-retrieval-and-practice.html)。VLAD跟BOW差不多，只不过将词频统计，变为了残差累加。我github项目上有很多关于检索的项目，可以看看。

**Comment by xxllp** [comment]
有个问题哈，sift 获取的特征超过千万，然后kmeans 数据太大会失败了，有人告诉我可以抽样一部分图片就可以了，这个有啥好办法解决吗

**Comment by xxllp** [comment]
还有这个如果效果不好的话可以通过调参来修改吗

**Comment by willard-yuan** [comment]
你要做什么？如果是要在实际项目里用，用深度学习搞特征。

**Comment by xxllp** [comment]
图像去重，数据量不大10w，深度学习不行吧，我测试了没啥用。

**Comment by xxllp** [comment]
但是这个重复不是完全一样，是大部分区域一样

**Comment by willard-yuan** [comment]
10万不到的话，可以用local feature搞。local feature直接做索引，不用对local feauture做
aggregation了。

**Comment by xxllp** [comment]
直接做索引？？？？sift这种怎么直接做索引

**Comment by willard-yuan** [comment]
可以参考这个[hnsw_sifts_retrieval](https://github.com/willard-yuan/cvtk/tree/master/hnsw_sifts_retrieval)。

**Comment by xxllp** [comment]
多谢，我现在用orb +vlad 搞了一套东西~~

**Comment by xxllp** [comment]
有个比较奇怪的现象，sift等这套特征提取算法 对图片中都是文字的表现出来的效果不是很好

**Comment by willard-yuan** [comment]
文字匹配上，这种是正常的，符合预期

**Comment by xxllp** [comment]
有那种根据文字搜索图片的数据吗

**Comment by willard-yuan** [comment]
没有这样的数据。
